# version: '2.6'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    networks:
      - video-chat-network


  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - video-chat-network

networks:
video-chat-network:


