version: '3'

services:
  frontend:
    build:
      context: .frontend/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - video-chat-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - video-chat-network

networks:
  video-chat-network:
